### ISSUE TITLE
re https://github.com/elttam/advisories/blob/master/RetroShare%20Advisory%20-%20elttam.pdf

### ISSUE THREAD

**Issue by dtschmitz** [elttam/advisories#1]
Hello,
Thank you for providing vulnerability testing against the Retroshare project.

Please provide a complete set of documentation for the environment, toolset, settings used to obtain your testbed results for Retroshare, to the extent that we may want to replicate the same tests to ensure ongoing certification.

Sincerely,
Dietrich

**Comment by dtschmitz** [comment]
Why did you close this issue?

**Comment by danielhodson** [comment]
Hi Dietrich - can you please elaborate on what ongoing certification you are referring to?

The process of vulnerability discovery was manual, although we have documented our approach and recommendations which you might find useful [here](https://www.elttam.com.au/blog/a-review-of-the-eff-secure-messaging-scorecard-pt1/).

No special tools or settings were used - the binaries were compiled on Linux with debugging info, communication was between two clients on the same network, and exploitation was performed through gdb at various entry points (unless documented otherwise in our advisory).

Happy to help with any other questions - hope this helps :)

Thanks,
Dan
